### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by Harry9494** [rmartin5/aqua-sim-ng#17]
aqua-sim-signal-cache.cc file does not complile.
error: 'creal' was not declared in this scope (line 423)
error: 'cexp' was not declared in this scope (line 429)

Would you know why I get this error?
I try to run it on Virtualbox (Fedora 30).

**Comment by shihchun** [comment]
I use vim to change that file `creal` to `std::real`, and the `cexp` to `exp`. and then it works with the Aqua-Sim-NG NS-3 V3.29 download from Zheng Peng's Wiki.

**Comment by 18845638173** [comment]
Hi,
I have been troubled by this problem for a long time.
Could you tell me how you solved it?

**Comment by shihchun** [comment]
https://shihchun.github.io/ns3_installation/

You should install NS3, build and make sure it module works on your machine
first.

Then debug with newest version they put on their website. Cuz the GCC
version and some dependency, u might need to modify something to make it
works. That’s what I did.


lzr ***@***.***>於 2021年5月19日 週三，下午3:25寫道：

**Comment by shihchun** [comment]
Follow the install guide to install the ns3

[ns3 official guide](https://www.nsnam.org/wiki/Installation)

[my blog](https://shihchun.github.io/ns3_installation/)

[![asciicast](https://asciinema.org/a/eOFGEwuL947wtvWKrFTR4pnwy.svg)](https://asciinema.org/a/eOFGEwuL947wtvWKrFTR4pnwy)

You should install NS3, build and make sure it module works on your machine
first.

Then debug with newest version with ns3 3.29, I download from Zheng Peng's Wiki, but it might not available now.

but files still here.

```sh
wget http://hudson.ccny.cuny.edu/download/aquasim-ng.tgz
```

Cuz the GCC version and some dependency, u might need to modify something to make it
works. That’s what I did.

for example real -> std::real, cexp -> exp, ... etc...
